id: P3914111A
initial_creation_type: ocr
source_metadata:
  volumes:
    3804e9b88b8a478fbf98d67357be3b9f:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: དཔལ་གསང་བ་འདུས་པའི་རྒྱུད་ཀྱི་རྒྱུད་འགྲེལ།
      total_pages: 1453
      volume_number: 15
